class RequestCode:
    REGISTRATION_REQUEST = 825
    RECEIVE_PUBLIC_KEY = 826
    LOGIN_REQUEST = 827
    SAVE_FILE_REQUEST = 828
    FILE_TRANSFER_SUCCESS = 900
    CRC_MISMATCH = 901
    FILE_TRANSFER_FAILED = 902

class ResponseCode:
    pass
